version: "3.8"
services:
  database:
    image: mongo
    container_name: mymongodb
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - D:/Devops/New folder/docker_mongo/db:/data/db:/data/db

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    ports:
      - 3000:3000
    # adding the mount volume point which we create earlier
    volumes:
      - D:/Devops/New folder/docker_mongo/grafana:/var/lib/grafana